name: Build Android APK

on:
  push:
    branches: [ main ]

env:
  ANDROID_HOME: /usr/local/android-sdk
  PATH: $ANDROID_HOME/cmdline-tools/latest/bin:$PATH:/usr/bin:/bin

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Install essential tools (with verification)
      run: |
        sudo apt-get update
        # 安装基础工具并验证
        if ! sudo apt-get install -y \
          tar gzip zip unzip \
          xz-utils bzip2; then
          echo "::error::Failed to install core utilities"
          exit 1
        fi
        
        # 双重验证tar是否可用
        if ! command -v tar >/dev/null 2>&1; then
          echo "::error::tar still not found after installation"
          echo "Searching for tar..."
          sudo find / -name "tar" 2>/dev/null || true
          exit 1
        fi

    - name: Verify tool availability
      run: |
        echo "=== Essential tools verification ==="
        command -v tar && tar --version
        command -v gzip && gzip --version
        command -v unzip && unzip -v
        echo "PATH: $PATH"

    - name: Install system dependencies
      run: |
        sudo apt-get install -y \
          git openjdk-17-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev libncurses5-dev \
          libtinfo6 cmake libffi-dev libssl-dev \
          libxml2-dev libxslt-dev

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Android SDK
      run: |
        sudo mkdir -p $ANDROID_HOME
        sudo chmod -R 777 $ANDROID_HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | sdkmanager --licenses > /dev/null 2>&1
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip wheel
        pip install --no-cache-dir \
          buildozer==1.5.0 \
          cython==0.29.33

    - name: Initialize Buildozer
      run: |
        buildozer android update
        buildozer check

    - name: Build APK (with retry)
      run: |
        for i in {1..3}; do
          buildozer -v android clean && \
          buildozer -v android debug 2>&1 | tee build.log && \
          ([ -f bin/*.apk ] || (cat build.log && exit 1)) && break
          echo "Build attempt $i failed, retrying..."
          sleep 15
        done

    - name: Verify APK
      run: |
        ls -lh bin/
        $ANDROID_HOME/build-tools/34.0.0/aapt dump badging bin/*.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: comic-reader-apk
        path: bin/*.apk
        retention-days: 7
        if-no-files-found: error
